Feat/b-utton
shaf-i/alshaf-i-pwa pull request #1
Opened 2022-06-05 14:13 UTC by MM25Zamanian

## Description

Button Web Components

## PR Checklist

- [x] The commit message follows our guidelines: <https://github.com/shaf-i/alshaf-i-pwa/blob/main/CONTRIBUTING.md#commit-message-format>
- [x] All methods have proper description in `jsdocs` format with `@example` section.
- [x] Docs have been added / updated (for bug fixes / features).
- [x] I have performed a self-review of my own code.

2022-06-05 14:17 UTC, njfamirm commented
لطفا مایل استون ها رو با فرمت Before vx.x.x بزن!

2022-06-05 14:18 UTC, njfamirm commented
دلیلی داره b-tton?

2022-06-05 14:37 UTC, njfamirm commented
چرا برای نصب یک پکیج کامیت میکنی؟
چیز خاصی نیست فکر نکنم لازم باشه

همچنین برای کامیت اخر باید کامیتت رو تصحیح میکردی نه اینکه یک کامیت جدید بزنی

2022-06-05 14:52 UTC, njfamirm requested changes

2022-06-05 14:52 UTC, njfamirm commented on src/elements/b-utton.ts
> +}
چرا بالای کلس؟

2022-06-05 14:52 UTC, njfamirm commented on src/elements/b-utton.ts
> +      padding: var(--gap, 4px 8px 12px);
یک Enter ):

2022-06-05 14:52 UTC, njfamirm commented on src/elements/b-utton.ts
> +      --base-color-contrast: var(--primary-color-contrast);
اینا اینجا چرا تعریف شده؟
برای کل پروژه لازمه
باید توی فایل css اصلی نوشته بشه

2022-06-05 14:52 UTC, njfamirm commented on src/elements/b-utton.ts
> +  }
فکر میکنم بتونی اینو راحت تر توی خود html هندل کنی

```ts
${!this.shouldRenderRipple 
   ? html`<mwc-ripple ?disabled="${this.disabled}"></mwc-ripple>`  
   : html``
}
```

https://github.com/njfamirm/Sunglasses/blob/2a8f3d82d2f848cfebf2e3d1bf5897855301d546/packages/sunglasses-web/src/elements/tweet-container.ts#L164

2022-06-05 14:55 UTC, MM25Zamanian commented on src/elements/b-utton.ts
> +  }
۱. از لحاظ خوانایی این خیلی بهتره
۲. لطفا از html string خالی استفاده نکن، طبق مستندات لیت باید از nothing استفاده کنیم

2022-06-05 14:56 UTC, MM25Zamanian commented on src/elements/b-utton.ts
> +      --base-color-contrast: var(--primary-color-contrast);
داری اشتباه میزنی داداش
پرایمری کالر در کل پروژه تعریف میشه ولی بیس کالر واسه هر کامپوننت جداست (طبق آیونیک)

واسه همین گفتم شخصی سازی خیلی خوبی داریم

2022-06-05 14:57 UTC, MM25Zamanian commented on src/elements/b-utton.ts
> +}
۱. خود الوتر همین شکلیه
۲. فرقی نداره کجا باشه

2022-06-05 15:03 UTC, njfamirm commented on src/elements/b-utton.ts
> +}
https://cs.github.com/lit/lit.dev/blob/5326c28fa5354875b47dec68bdd0b8acf5c3aa68/packages/lit-dev-content/src/components/litdev-flyout.ts#L169

چه فرقی دار چیه
همه چی باید با نظم باشه 😃

2022-06-05 15:04 UTC, njfamirm commented on src/elements/b-utton.ts
> +      --base-color-contrast: var(--primary-color-contrast);
راس میگی اشتباه دیدم

2022-06-05 15:05 UTC, njfamirm commented on src/elements/b-utton.ts
> +  }
موافق خوانایی نیستم
الکی فانکشن درست کردی

۲. اوکی

بنظرم باید تغییر کنه

2022-06-05 15:07 UTC, MM25Zamanian commented on src/elements/b-utton.ts
> +  }
پیشنهاد میکنم یه نفر دیگه ریویو کنه که یکم ضعیف تر باشه
@sahbaee

2022-06-05 15:07 UTC, njfamirm commented
چرا ورژن 0.9.0 ؟

2022-06-05 15:07 UTC, MM25Zamanian commented on src/elements/b-utton.ts
> +      padding: var(--gap, 4px 8px 12px);
متوجه نشدم

2022-06-05 15:07 UTC, MM25Zamanian commented on src/elements/b-utton.ts
> +}
لطفا بعد از گرفتن نظر علی میهن دوست، یه تسک ثبت کن یه همه کامپوننت ها ریفکتور بشه

2022-06-05 15:08 UTC, MM25Zamanian commented
> چرا ورژن 0.9.0 ؟

مهم نیست چیه خودت تغییرش بده

2022-06-05 15:11 UTC, njfamirm commented on src/elements/b-utton.ts
> +}
کد لیت فرستادم
فک کنم معتبر باشه

2022-06-05 15:12 UTC, njfamirm commented on src/elements/b-utton.ts
> +      padding: var(--gap, 4px 8px 12px);
اشتباه لینک دادم

2022-06-05 15:12 UTC, njfamirm commented on src/elements/b-utton.ts
> +  }
بازم موافق نیستم
این مورد رو باید بپرسیم

2022-06-05 15:13 UTC, MM25Zamanian commented on src/elements/b-utton.ts
> +  }
با این مورد موافقم

2022-06-05 15:15 UTC, MM25Zamanian commented on src/elements/b-utton.ts
> +}
ببین من جفت این حالت هارو از کمپانی های بزرگ دیدم
پس احتمالا سلیقه ای هستش
بهتره با الوتر یکی باشه
یا یه تسک ثبت کن که راجبش تحقیق کنیم؟

2022-06-06 18:15 UTC, njfamirm approved these changes

2022-06-06 18:15 UTC, njfamirm commented on src/elements/b-utton.ts
> +}
اینم قانع شدم
بالای فایل یسری ایمپورت که نمیخونیم
اینم چیزیه که لازم نیست موقع سورس خوندن بخونیم
پس همون بالا باشه بهتره

2022-06-06 20:27 UTC, merged